-- CREATE HOLDER/DNG_HOLDER/ACCOUNT by SUJIN
CREATE HOLDER(
	H_ID CHAR(9) NOT NULL,
	ADDRESS VARCHAR2(50),
	COUNTRY VARCHAR2(20) NOT NULL,
	PHONE_NUMBER VARCHAR2(20) NOT NULL,
	PRIMARY KEY(H_ID),
	UNIQUE(PHONE_NUMBER)
);

CREATE DNG_HOLDER(
	H_ID CHAR(9) NOT NULL,
	SCORE NUMBER NOT NULL,
	PRIMARY KEY(H_ID),
);

CREATE ACCOUNT(
	ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
	BALANCE NUMBER,
	PASSWORD NOT NULL,
	PRIMARY KEY(ACCOUNT_NUMBER)
);

-- ADD FOREIGN KEY (DNG_HODER, ACCOUNT) by SUJIN
ALERT TABLE DNG_HOLDER ADD FOREIGN KEY (H_ID) 
REFERENCES HOLDER(H_ID) ON DELETE SET NULL;

ALERT TABLE ACCOUNT ADD FOREIGN KEY (H_ID) 
REFERENCES HOLDER(H_ID) ON DELETE SET NULL;
